export const SET_AUTOCOMPLETE_LIST = 'SET_AUTOCOMPLETE_LIST';
export const SET_WEATHER_DATA = 'SET_WEATHER_DATA';
export const SET_FORECAST_DATA = 'SET_FORECAST_DATA';
export const CHANGE_COUNTRY = 'CHANGE_COUNTRY';
export const ADD_COUNTRY_LIST = 'ADD_COUNTRY_LIST';
export const DELETE_COUNTRY_LIST = 'DELETE_COUNTRY_LIST';
